spring:
  application:
    name: ngcca-security
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      database: ${ngcca.mongodb.database:}
      host: ${ngcca.mongodb.host:}
      port: ${ngcca.mongodb.port:}
      password: ${ngcca.mongodb.password:}
      username: ${ngcca.mongodb.username:}
      auto-index-creation: true
      authentication-database: admin
ngcca:
  security:
    enabled: true
    jwt:
      algorithm: 'HS512'
      sign-key: "!@#$%^&*(NGCCA)!@#$%^&*(NGCCA)!@#$%^&*(NGCCA)"
    ignored:
      urls:
        - "/swagger**/**"
        - "/v3/api-docs/**"
        - "/favicon.ico"
        - "/pub"
        - "/**/login"
server:
  port: 8070