# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Docker.gitlab-ci.yml

# Build a Docker image with CI/CD and push to the GitLab registry.
# Docker-in-Docker documentation: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
#
# This template uses one generic job with conditional builds
# for the default branch and all other (MR) branches.

stages:
  - test
  - build

test:
  stage: test
  script:
    - mvn -s .m2/settings.xml -Dmaven.repo.local=.m2/repository clean test
  only:
    - main

cache:
  key: ngcca-ci-cache
  paths:
    - .m2/repository/

build_jar:
  image: 119.91.214.25:5000/library/maven:3.8-openjdk-17-slim
  stage: build
  script:
    - mvn -s .m2/settings.xml -Dmaven.repo.local=.m2/repository -Dmaven.test.skip=true clean package

build_image:
  image: docker:latest
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - export IMAGE=$CI_REGISTRY/ngcca/ngcca-server:$(date '+%Y%m%d%H%M%S')
    - docker build -t $IMAGE .
    - docker push $IMAGE

