# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Docker.gitlab-ci.yml

# Build a Docker image with CI/CD and push to the GitLab registry.
# Docker-in-Docker documentation: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
#
# This template uses one generic job with conditional builds
# for the default branch and all other (MR) branches.

cache:
  key: ngcca-ci-cache
  paths:
    - .m2/repository/

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --threads 1C"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

#image: maven:3.8-openjdk-17-slim

stages:
  #  - build
  #  - test
  #  - package
  #  - image-push
  - deploy

#build:
#  stage: build
#  script:
#    - mvn $MAVEN_CLI_OPTS $MAVEN_OPTS clean compile
#  only:
#    - main
#
#test:
#  stage: test
#  script:
#    - mvn $MAVEN_CLI_OPTS $MAVEN_OPTS test
#  only:
#    - main
#
#package:
#  stage: package
#  only:
#    - main
#  script:
#    - mvn $MAVEN_CLI_OPTS $MAVEN_OPTS -Dmaven.test.skip=true package
#  artifacts:
#    paths:
#      - ngcca-server/target/ngcca-server.jar
#
#docker-build:
#  image: docker:latest
#  stage: image-push
#  services:
#    - name: docker:dind
#      command: [ "--insecure-registry","119.91.214.25:5000" ]
#
#  before_script:
#    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
#  script:
#    - export IMAGE=$CI_REGISTRY/ngcca/ngcca-server:$(date '+%Y%m%d%H%M%S')
#    - docker build -t $IMAGE .
#    - docker push $IMAGE

deploy:
  image: ubuntu
  stage: deploy
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -p 26889 root@119.91.214.25
    - kubectl get pods -n ngcca-system