apiVersion: v1
kind: Namespace
metadata:
  labels:
    k8s-app: hotcloud-buildpack
  name: hotcloud
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    k8s-app: hotcloud-buildpack
  name: hotcloud-buildpack-job
  namespace: hotcloud
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 3
  activeDeadlineSeconds: 1800
  template:
    spec:
      containers:
        - name: hotcloud-buildpack
          image: gcr.io/kaniko-project/executor:latest
          imagePullPolicy: IfNotPresent
          args:
            - --dockerfile=Dockerfile
            - --insecure-registry=docker-registry-idc01-sz.cloudtogo.cn
            - --context=git://gitee.com/yannanshan/devops-thymeleaf.git#refs/heads/master
            - --destination=yaolianhua/devops-thymeleaf:0.1
          volumeMounts:
            - name: docker-registry-secret-volume
              mountPath: /kaniko/.docker
      restartPolicy: Never
      volumes:
        - name: docker-registry-secret-volume
          secret:
            secretName: docker-registry-secret
            items:
              - key: .dockerconfigjson
                path: config.json
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: hotcloud-buildpack
  name: docker-registry-secret
  namespace: hotcloud
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "your registry auth info"