ngcca:
  redis:
    database: 0
    password: QbMufCD@9WVQ^Hv
    host: mid.vps-a.linux
    port: 6379
  registry:
    url: 119.91.214.25:5000
    username: admin
    password: "QbMufCD@9WVQ^Hv"
    imagebuild-namespace: image-build
  minio:
    access-key: admin
    secret-key: "QbMufCD@9WVQ^Hv"
    endpoint: "http://mid.vps-a.linux:9009"
  mongodb:
    uri: "mongodb://admin:QbMufCD%409WVQ^Hv@mid.vps-a.linux:27017/ngcca?authSource=admin"

  kubernetes-agent:
    endpoint: http://k8s-agent.vps.tencent
  web-server:
    host:
    port:
    endpoint: http://localhost:4000
  application:
    dot-suffix-domain: ".vps.linux"
    deployment-timeout-second: 7200
  security:
    enabled: true
    ignored-defaults:
      - "/swagger**/**"
      - "/v3/api-docs/**"
      - "/favicon.ico"
      - "/pub"
      - "/**/login"
      - "/plugins/**"
      - "/js/**"
      - "/dist/**"
    ignored-urls:
      - "/index"
      - "/**/logout"
      - "/administrator/**"
      - "/templates/**"
      - "/user/**"
      - "/"
    oauth2:
      github:
        client-id: "241c6168a7efeaf852ba"
        client-secret: "b3f98e25f25aa0807a0bc49c126178a11417e046"
      gitlab:
        client-id: "7a8680a3321f9ef21ce05f1746bb50a15ba8240818794f3e222af902043306d5"
        client-secret: "gloas-b962f886b24167b29f177d95d0fde8326c3ce45f3bb3e6b6650ee734a6905878"
        redirect-uri: "${ngcca.web-server.endpoint}/login/oauth2/code/gitlab"
  buildpack:
    build-timeout-second: 3600
logging:
  level:
    io.hotcloud.common.log: debug
    com.github.dockerjava.api.command: debug
    com.github.dockerjava.core.command: debug


