spring:
  application:
    name: @artifactId@
  profiles:
    include: system-registry-image
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      uri: ${ngcca.mongodb.uri}
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB
  thymeleaf:
    cache: false
  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      config:
        import-check:
          enabled: false
server:
  port: 4000

