spring:
  application:
    name: ngcca
  profiles:
    include: system-registry-image
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      uri: ${ngcca.mongodb.uri}
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB
  thymeleaf:
    cache: false
server:
  port: 4000

ngcca:
  redis:
    database:
    password:
    host:
    port:
  registry:
    url:
    username:
    password:
    imagebuild-namespace:
  minio:
    access-key:
    secret-key:
    endpoint:
  mongodb:
    uri:
  kubernetes-agent:
    host:
    port:
    domain-name:
  buildpack:
    build-timeout-second: 1200
  application:
    deployment-timeout-second: 1200
    dot-suffix-domain: ".k8s.local"
  security:
    enabled: true
    ignored-defaults:
      - "/swagger**/**"
      - "/v3/api-docs/**"
      - "/favicon.ico"
      - "/pub"
      - "/**/login"
      - "/plugins/**"
      - "/js/**"
      - "/dist/**"
    ignored-urls:
      - "/index"
      - "/administrator/**"
      - "/template/**"
      - "/"
  openai:
    http-client-timeout-seconds: 60
    http-proxy:
      hostname:
      port:
    api-key:
  docker:
    host:
    pull-timeout-seconds:
    push-timeout-seconds:

  web-server:
    host:
    port:
    endpoint:
logging:
  level:
    io.hotcloud.common.log: info
    com.github.dockerjava.api.command: info
    com.github.dockerjava.core.command: info

