kubernetes:
  in-cluster: false
  enable-workloads-watcher: true
message:
  type: rabbitmq
  rabbitmq:
    host: localhost
    username: admin
    password: QbMufCD@9WVQ^Hv
    port: 5672
cache:
  type: redis
  redis:
    host: localhost
    port: 6379
    password: QbMufCD@9WVQ^Hv
    database: 15
db:
  type: mongodb
  mongodb:
    host: localhost
    username: admin
    password: QbMufCD@9WVQ^Hv
    port: 27017
    database: hotcloud-dev
  redis:
    database: 0
    password: QbMufCD@9WVQ^Hv
    host: localhost
    port: 6379
minio:
  access-key: admin
  secret-key: QbMufCD@9WVQ^Hv
  endpoint: "http://localhost:9009"
buildpack:
  registry:
    url: 192.168.146.128:5000
    project: image-build-dev
    username: admin
    password: QbMufCD@9WVQ^Hv
    kaniko-image-url: 192.168.146.128:5000/base/imagebuild:latest
    git-init-container-image-url: 192.168.146.128:5000/base/git:latest
    alpine-init-container-image-url: 192.168.146.128:5000/base/alpine:latest
    java-base-image: 192.168.146.128:5000/base/java11:tomcat9.0-openjdk11
app:
  dot-suffix-domain: .k8s-cluster.com