spring:
  application:
    name: hotcloud
  config:
    import:
      - application-allinone.yml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  rabbitmq:
    host: ${message.rabbitmq.host:}
    port: ${message.rabbitmq.port:}
    username: ${message.rabbitmq.username:}
    password: ${message.rabbitmq.password:}
    virtual-host: /
  data:
    mongodb:
      database: ${db.mongodb.database:}
      host: ${db.mongodb.host:}
      port: ${db.mongodb.port:}
      password: ${db.mongodb.password:}
      username: ${db.mongodb.username:}
      auto-index-creation: true
      authentication-database: admin
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB
server:
  max-http-header-size: 40KB
logging:
  level:
    io.hotcloud.kubernetes.server: info
    io.hotcloud.buildpack.server: info
    io.hotcloud.security.admin: info
    io.hotcloud.db.server: info
    io.hotcloud.common: info