spring:
  application:
    name: ngcca-server
  config:
    import:
      - application-allinone.yml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  rabbitmq:
    host: ${ngcca.rabbitmq.host:}
    port: ${ngcca.rabbitmq.port:}
    username: ${ngcca.rabbitmq.username:}
    password: ${ngcca.rabbitmq.password:}
    virtual-host: /
  data:
    mongodb:
      database: ${ngcca.mongodb.database:}
      host: ${ngcca.mongodb.host:}
      port: ${ngcca.mongodb.port:}
      password: ${ngcca.mongodb.password:}
      username: ${ngcca.mongodb.username:}
      auto-index-creation: true
      authentication-database: admin
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB
server:
  max-http-header-size: 40KB