apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: web-server
  name: web-server
  namespace: ngcca-system
spec:
  ports:
    - name: http
      port: 4000
      protocol: TCP
      targetPort: http
      nodePort: 31004
  selector:
    k8s-app: web-server
  type: NodePort
  sessionAffinity: None
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-server
  namespace: ngcca-system
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  rules:
    - host: ngcca-ui.docker.desktop
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: web-server
                port:
                  number: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: web-server
  name: web-server
  namespace: ngcca-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: web-server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: web-server
    spec:
      #      hostAliases:
      #        - ip: 192.168.110.233
      #          hostnames:
      #            - harbor.linux-local
      #            - linux.local
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
              weight: 1
      containers:
        - image: 119.91.214.25:5000/ngcca/web-server:2023.10.24.180620
          imagePullPolicy: IfNotPresent
          name: web-server
          ports:
            - containerPort: 4000
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /web-server/config
              name: web-server-config-volume
              readOnly: false
      volumes:
        - configMap:
            name: web-server-config
            items:
              - key: config
                path: application.yml
          name: web-server-config-volume
---
apiVersion: v1
data:
  config: |
    ngcca:
      redis:
        database: 0
        password: QbMufCD@9WVQ^Hv
        host: 120.78.225.168
        port: 6379
      registry:
        url: 119.91.214.25:5000
        username: admin
        password: "QbMufCD@9WVQ^Hv"
        imagebuild-namespace: image-build
      minio:
        access-key: admin
        secret-key: "QbMufCD@9WVQ^Hv"
        endpoint: "http://120.78.225.168:9009"
      mongodb:
        uri: "mongodb://admin:QbMufCD%409WVQ^Hv@120.78.225.168:27017/ngcca?authSource=admin"
      openai:
        api-key: no-key
        http-proxy:
          hostname: localhost
          port: 0
        http-client-timeout-seconds: 60
      docker:
        host: "tcp://120.78.225.168:2375"
        pull-timeout-seconds: 300
        push-timeout-seconds: 300
    
      kubernetes-agent:
        host: 119.91.214.25
        port: 31400
        domain-name: 
      web-server:
        host: 
        port: 
        endpoint: "http://ngcca-ui.docker.desktop"
      application:
        dot-suffix-domain: ".vps.linux"
        deployment-timeout-second: 1200
      security:
        enabled: true
        ignored-defaults:
          - "/swagger**/**"
          - "/v3/api-docs/**"
          - "/favicon.ico"
          - "/pub"
          - "/**/login"
          - "/plugins/**"
          - "/js/**"
          - "/dist/**"
        ignored-urls:
          - "/index"
          - "/**/logout"
          - "/administrator/**"
          - "/templates/**"
          - "/user/templates/**"
          - "/user/applications/**"
          - "/"
      buildpack:
        build-timeout-second: 1800
    logging:
      level:
        io.hotcloud.common.log: debug
        com.github.dockerjava.api.command: debug
        com.github.dockerjava.core.command: debug
kind: ConfigMap
metadata:
  name: web-server-config
  namespace: ngcca-system
