
ngcca:
  redis:
    host: linux.local
    port: 6379
    password: QbMufCD@9WVQ^Hv
    database: 0
  kubernetes:
    in-cluster: false
    enable-workloads-watcher: true
    cluster-id: default-cluster
logging:
  level:
    io.hotcloud.common.log: debug