apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ngcca-admin
rules:
  - apiGroups: [ "" ]
    resources: [ "*" ]
    verbs: [ "*" ]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ngcca-admin
  namespace: ngcca-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ngcca-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ngcca-admin
subjects:
  - kind: ServiceAccount
    name: ngcca-admin
    namespace: ngcca-system