apiVersion: v1
kind: PersistentVolume
metadata:
  name: ngcca-data
  labels:
    type: local
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: ngcca-data=pvc
    namespace: ngcca-system
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /ngcca-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: storage-node/hostname
              operator: Exists
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ngcca-data-pvc
  namespace: ngcca-system
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi