apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: ngcca-server
  name: ngcca-server
  namespace: ngcca-system
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    k8s-app: ngcca-server
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ngcca-server
  namespace: ngcca-system
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  rules:
    - host: ngcca-server.linux
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: ngcca-server
                port:
                  number: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: ngcca-server
  name: ngcca-server
  namespace: ngcca-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: ngcca-server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: ngcca-server
    spec:
      #      hostAliases:
      #        - ip: 192.168.110.233
      #          hostnames:
      #            - harbor.linux-local
      #            - linux.local

      containers:
        - image: harbor.linux-local:5000/ngcca/core-server:2023.06.06.165020
          imagePullPolicy: IfNotPresent
          name: ngcca-server
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /core-server/config
              name: ngcca-server-config-volume
              readOnly: false
      volumes:
        - configMap:
            name: ngcca-server-config
            items:
              - key: config
                path: application.yml
          name: ngcca-server-config-volume
---
apiVersion: v1
data:
  config: |
    ngcca:
      redis:
        database: 0
        password: "QbMufCD@9WVQ^Hv"
        host: 120.78.225.168
        port: 6379
      registry:
        url: 119.91.214.25:5000
        username: admin
        password: "QbMufCD@9WVQ^Hv"
        imagebuild-namespace: image-build
      minio:
        access-key: admin
        secret-key: "QbMufCD@9WVQ^Hv"
        endpoint: "http://120.78.225.168:9009"
      mongodb:
        uri: "mongodb://admin:QbMufCD%409WVQ^Hv@120.78.225.168:27017/ngcca?authSource=admin"
      kubernetes-agent:
        endpoint: http://119.91.214.25:1400
      application:
        dot-suffix-domain: ".ngcca.linux"
    server:
      port: 8080
    logging:
      level:
        io.hotcloud.common.log: debug
        com.github.dockerjava.api.command: debug
        com.github.dockerjava.core.command: debug
kind: ConfigMap
metadata:
  name: ngcca-server-config
  namespace: ngcca-system
