spring:
  application:
    name: core-server
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      database: ${ngcca.mongodb.database:}
      host: ${ngcca.mongodb.host:}
      port: ${ngcca.mongodb.port:}
      password: ${ngcca.mongodb.password:}
      username: ${ngcca.mongodb.username:}
      auto-index-creation: true
      authentication-database: admin
  profiles:
    include: system-registry-image
ngcca:
  redis:
    database:
    password:
    host:
    port:
  registry:
    url:
    username:
    password:
    imagebuild-namespace:
  minio:
    access-key:
    secret-key:
    endpoint:
  mongodb:
    host:
    username:
    password:
    port:
    database:
  kubernetes-agent:
    host: localhost
    port: 1400
    domain-name:
  buildpack:
    build-timeout-second: 1200
  application:
    deployment-timeout-second: 1200
    dot-suffix-domain: ".k8s.local"
  security:
    enabled: true
    ignored-defaults:
      - "/swagger**/**"
      - "/v3/api-docs/**"
      - "/favicon.ico"
      - "/pub"
      - "/**/login"
    ignored-urls:
server:
  port: 8080
