ngcca:
  redis:
    database: 0
    password: QbMufCD@9WVQ^Hv
    host: linux.local
    port: 6379
  registry:
    url: harbor.linux-local:5000
    username: admin
    password: QbMufCD@9WVQ^Hv
    imagebuild-namespace: image-build-dev
  minio:
    access-key: admin
    secret-key: QbMufCD@9WVQ^Hv
    endpoint: "http://linux.local:9009"
  mongodb:
    host: linux.local
    username: admin
    password: QbMufCD@9WVQ^Hv
    port: 27017
    database: ngcca-dev
logging:
  level:
    io.hotcloud.common.log: debug


