kubernetes:
  in-cluster: false
message:
  type: rabbitmq
  rabbitmq:
    host: localhost
    username: root
    password: password
    port: 5672
logging:
  level:
    io.hotcloud.server: debug
    io.hotcloud.message: debug