kubernetes:
  in-cluster: false
  enable-workloads-watcher: true
message:
  type: websocket
  rabbitmq:
    host: localhost
    username: admin
    password: QbMufCD@9WVQ^Hv
    port: 5672
cache:
  type: redis
  redis:
    host: localhost
    port: 6379
    password: QbMufCD@9WVQ^Hv
    database: 15
db:
  type: redis
  mongodb:
    host: localhost
    username: admin
    password: QbMufCD@9WVQ^Hv
    port: 27017
    database: hotcloud
  redis:
    database: 0
    password: QbMufCD@9WVQ^Hv
    host: localhost
    port: 6379
buildpack:
  storage:
    type: nfs
    nfs-server: 119.91.214.25
  kaniko:
    verbosity: info
