kubernetes:
  in-cluster: false
  enable-workloads-watcher: true
message:
  type: rabbitmq
  rabbitmq:
    host: localhost
    username: admin
    password: QbMufCD@9WVQ^Hv
    port: 5672
cache:
  type: redis
  redis:
    host: localhost
    port: 6379
    password: QbMufCD@9WVQ^Hv
    database: 15
logging:
  level:
    io.hotcloud.kubernetes.server: debug
    io.hotcloud.buildpack.server: debug
    io.hotcloud.message: info
security:
  jwt:
    algorithm: HS512
    sign-key: QWERTYUIOPASDFGHJKLZXCVBNMmnbvcxzlkjhgfdsapoiuytrewq
