spring:
  application:
    name: hotcloud
  profiles:
    include:
      - kubernetes
      - buildpack
      - message
      - security
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  rabbitmq:
    host: ${message.rabbitmq.host:}
    port: ${message.rabbitmq.port:}
    username: ${message.rabbitmq.username:}
    password: ${message.rabbitmq.password:}
    virtual-host: /
## log level
logging:
  level:
    io.hotcloud.kubernetes.server: debug
    io.hotcloud.buildpack.server: debug
    io.hotcloud.message: info