kubernetes:
  in-cluster: false
  enable-workloads-watcher: true
message:
  type: rabbitmq
  rabbitmq:
    host: 120.78.225.168
    username: admin
    password: QbMufCD@9WVQ^Hv
    port: 5672
cache:
  type: redis
  redis:
    host: 120.78.225.168
    port: 6379
    password: QbMufCD@9WVQ^Hv
    database: 15
db:
  type: mongodb
  mongodb:
    host: 120.78.225.168
    username: admin
    password: QbMufCD@9WVQ^Hv
    port: 27017
    database: hotcloud-dev
  redis:
    database: 0
    password: QbMufCD@9WVQ^Hv
    host: 120.78.225.168
    port: 6379
minio:
  access-key: admin
  secret-key: QbMufCD@9WVQ^Hv
  endpoint: "http://120.78.225.168:9009"
buildpack:
  storage:
    type: nfs
    nfs-server: 119.91.214.25
  registry:
    url: 119.91.214.25:5000
    project: dev
    username: admin
    password: QbMufCD@9WVQ^Hv
app:
  storage:
    type: nfs
    nfs-server: 119.91.214.25
