spring:
  application:
    name: hotcloud
  profiles:
    include:
      - kubernetes
      - buildpack
      - message
      - cache
      - security
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  rabbitmq:
    host: ${message.rabbitmq.host:}
    port: ${message.rabbitmq.port:}
    username: ${message.rabbitmq.username:}
    password: ${message.rabbitmq.password:}
    virtual-host: /
  redis:
    database: ${cache.redis.database:}
    password: ${cache.redis.password:}
    host: ${cache.redis.host:}
    port: ${cache.redis.port:}
    client-type: jedis
    jedis:
      pool:
        max-active: 50
        max-idle: 50
        min-idle: 50
server:
  max-http-header-size: 40KB
## log level
logging:
  level:
    io.hotcloud.kubernetes.server: debug
    io.hotcloud.buildpack.server: debug
    io.hotcloud.message: info