spring:
  application:
    name: hot-cloud
  profiles:
    include:
      - kubernetes
      - buildpack
  cloud:
    compatibility-verifier:
      enabled: false
## log level
logging:
  level:
    io.hotcloud.server: info