spring:
  application:
    name: hotcloud
  profiles:
    include:
      - kubernetes
      - buildpack
      - message
  rabbitmq:
    host: ${message.rabbitmq.host:}
    port: ${message.rabbitmq.port:}
    username: ${message.rabbitmq.username:}
    password: ${message.rabbitmq.password:}
    virtual-host: /
## log level
logging:
  level:
    io.hotcloud.server: debug
    io.hotcloud.message: info