spring:
  application:
    name: hotcloud
  profiles:
    include:
      - allinone
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  rabbitmq:
    host: ${message.rabbitmq.host:}
    port: ${message.rabbitmq.port:}
    username: ${message.rabbitmq.username:}
    password: ${message.rabbitmq.password:}
    virtual-host: /
  data:
    mongodb:
      database: hotcloud
      host: ${db.mongodb.host:}
      port: ${db.mongodb.port:}
      password: ${db.mongodb.password:}
      username: ${db.mongodb.username:}
      auto-index-creation: true
server:
  max-http-header-size: 40KB
logging:
  level:
    io.hotcloud.kubernetes.server: info
    io.hotcloud.buildpack.server: info
    io.hotcloud.security.admin: info
    io.hotcloud.db.server: info
    io.hotcloud.message: info