kubernetes:
  in-cluster: false
  enable-workloads-watcher: true
message:
  type: websocket
  rabbitmq:
    host: localhost
    username: root
    password: password
    port: 5672
logging:
  level:
    io.hotcloud.server: debug
    io.hotcloud.message: info