spring:
  application:
    name: ngcca-kubernetes-agent
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
kubernetes:
  in-cluster: true
  enable-workloads-watcher: true
  redis:
    database:
    host:
    port:
    password:
server:
  port: 1400
logging:
  level:
    io.hotcloud.common.log: info