spring:
  application:
    name: k8s-agent
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      config:
        import-check:
          enabled: false
server:
  port: 1400
logging:
  level:
    io.hotcloud.common.log: info