spring:
  application:
    name: ngcca-kubernetes-agent
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  rabbitmq:
    host: ${kubernetes.rabbitmq.host:}
    port: ${kubernetes.rabbitmq.port:}
    username: ${kubernetes.rabbitmq.username:}
    password: ${kubernetes.rabbitmq.password:}
    virtual-host: /
kubernetes:
  in-cluster: true
  enable-workloads-watcher: true
  rabbitmq:
    host:
    port:
    username:
    password:
server:
  port: 1400