spring:
  config:
    import:
      - optional:nacos:application-system-registry-image.yml
      - optional:nacos:${spring.application.name}.yml
  cloud:
    nacos:
      config:
        namespace: ${NACOS_NAMESPACE:08046fe8-abcd-4abd-9b77-120fbdfb9b95}
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}

