ngcca:
  redis:
    database: 0
    password: QbMufCD@9WVQ^Hv
    host: mid.vps-a.linux
    port: 6379
  registry:
    url: 119.91.214.25:5000
    username: admin
    password: "QbMufCD@9WVQ^Hv"
    imagebuild-namespace: image-build
  minio:
    access-key: admin
    secret-key: "QbMufCD@9WVQ^Hv"
    endpoint: "http://mid.vps-a.linux:9009"
  mongodb:
    uri: "mongodb://admin:QbMufCD%409WVQ^Hv@mid.vps-a.linux:27017/ngcca?authSource=admin"
  kubernetes-agent:
    endpoint: http://k8s-agent.vps.tencent
  application:
    dot-suffix-domain: ".vps.linux"
logging:
  level:
    io.hotcloud.common.log: debug
    com.github.dockerjava.api.command: debug
    com.github.dockerjava.core.command: debug


