name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Build the Docker image
      env:
        image: yaolianhua/hotcloud:$(date +%s)
        version: 0.1
      run: |
        docker build . --file localized.Dockerfile --build-arg HOTCLOUD_VERSION=$version --tag $image
        docker push $image
