name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#     - name: Set up JDK 11
#       uses: actions/setup-java@v2
#       with:
#         java-version: '11'
#         distribution: 'adopt'
#         cache: maven
#     - name: Build with Maven
#       run: mvn -B package --file pom.xml
    
    - name: Build the Docker image
      env:
        IMAGE: yaolianhua/hotcloud:${{ date '+%Y%m%d%H%M%S' }}
        VERSION: 0.1
      run: echo $IMAGE $VERSION
#       run: |
#         echo $image $version
#         docker build -f localized.Dockerfile --build-arg HOTCLOUD_VERSION=$VERSION -t $IMAGE .
#         docker push $IMAGE
