# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11.0.12'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B install --file pom.xml
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date '+%Y%m%d%H%M%S')"
    - name: Build the Docker image
      env:
        IMAGE: yaolianhua/hotcloud:${{ steps.date.outputs.date }}
        VERSION: 0.1
      run: |
        echo -e $IMAGE $VERSION
        docker build -f localized.Dockerfile --build-arg HOTCLOUD_VERSION=$VERSION -t $IMAGE .